/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms_Admin;

import com.toedter.calendar.JDateChooser;
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manu Kumar
 */
public class ViewAttendanceForm extends javax.swing.JPanel {

    /**
     * Creates new form ViewAttendanceForm
     */
    public ViewAttendanceForm() {
        initComponents();
        lblHeader.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        checkBoxState = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        checkBoxCountry = new javax.swing.JCheckBox();
        btnResetFilters = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        absentLBL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        presentLBL = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        lblAbsent = new javax.swing.JLabel();
        checkBoxEnrollmentNo = new javax.swing.JCheckBox();
        dateChooserTo = new com.toedter.calendar.JDateChooser();
        checkBoxCourse = new javax.swing.JCheckBox();
        dateChooserFrom = new com.toedter.calendar.JDateChooser();
        checkBoxDepartment = new javax.swing.JCheckBox();
        lblHeader = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        setMaximumSize(new java.awt.Dimension(969, 640));
        setMinimumSize(new java.awt.Dimension(969, 640));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        checkBoxState.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxState.setText("State");
        checkBoxState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxStateItemStateChanged(evt);
            }
        });
        checkBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxStateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("To");

        checkBoxCountry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxCountry.setText("Country");
        checkBoxCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxCountryItemStateChanged(evt);
            }
        });

        btnResetFilters.setBackground(new java.awt.Color(102, 102, 255));
        btnResetFilters.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnResetFilters.setText("Reset Filters");
        btnResetFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFiltersActionPerformed(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSearch.setText("Search");

        absentLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        absentLBL.setText("Absent :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("On / From");

        presentLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        presentLBL.setText("Present :");

        lblPresent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(0, 255, 0));
        lblPresent.setText("------");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        lblAbsent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 51, 51));
        lblAbsent.setText("------");

        checkBoxEnrollmentNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxEnrollmentNo.setText("Enrollment No");
        checkBoxEnrollmentNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxEnrollmentNoItemStateChanged(evt);
            }
        });

        dateChooserTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        checkBoxCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxCourse.setText("Course");
        checkBoxCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxCourseItemStateChanged(evt);
            }
        });
        checkBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCourseActionPerformed(evt);
            }
        });

        dateChooserFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        checkBoxDepartment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxDepartment.setText("Department");
        checkBoxDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxDepartmentItemStateChanged(evt);
            }
        });
        checkBoxDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDepartmentActionPerformed(evt);
            }
        });

        lblHeader.setBackground(new java.awt.Color(0, 51, 153));
        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("                                         Students Attendance Track");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(absentLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presentLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxDepartment)
                    .addComponent(checkBoxEnrollmentNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(presentLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absentLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(checkBoxEnrollmentNo)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxCourse)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxDepartment)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxState)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxCountry)))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

    }//GEN-LAST:event_txtSearchKeyReleased

    private void checkBoxStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxStateItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkBoxStateItemStateChanged

    private void checkBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxStateActionPerformed

    private void checkBoxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxCountryItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkBoxCountryItemStateChanged

    private void btnResetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFiltersActionPerformed
        txtSearch.setText("");
        dateChooserFrom.setDate(null);
        dateChooserTo.setDate(null);
        checkBoxEnrollmentNo.setSelected(false);
        checkBoxCourse.setSelected(false);
        checkBoxDepartment.setSelected(false);
        checkBoxState.setSelected(false);
        checkBoxCountry.setSelected(false);

        loadDataInTable();
    }//GEN-LAST:event_btnResetFiltersActionPerformed

    private void checkBoxEnrollmentNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxEnrollmentNoItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkBoxEnrollmentNoItemStateChanged

    private void checkBoxCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxCourseItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkBoxCourseItemStateChanged

    private void checkBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCourseActionPerformed

    private void checkBoxDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxDepartmentItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkBoxDepartmentItemStateChanged

    private void checkBoxDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxDepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absentLBL;
    private javax.swing.JButton btnResetFilters;
    private javax.swing.JCheckBox checkBoxCountry;
    private javax.swing.JCheckBox checkBoxCourse;
    private javax.swing.JCheckBox checkBoxDepartment;
    private javax.swing.JCheckBox checkBoxEnrollmentNo;
    private javax.swing.JCheckBox checkBoxState;
    private com.toedter.calendar.JDateChooser dateChooserFrom;
    private com.toedter.calendar.JDateChooser dateChooserTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel presentLBL;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable() {
        var columns = new ArrayList<>(Arrays.asList("Name", "Gender", "Email", "Date", "CheckIn", "Status"));

        String searchText = txtSearch.getText().trim();
        LocalDate fromDate = getLocalDate(dateChooserFrom);
        LocalDate toDate = getLocalDate(dateChooserTo);

        Long daysBetween = (fromDate != null && toDate != null) ? countWeekdays(fromDate, toDate) : null;

        Boolean enrollmentIncluded = checkBoxEnrollmentNo.isSelected();
        Boolean courseIncluded = checkBoxCourse.isSelected();
        Boolean departmentIncluded = checkBoxDepartment.isSelected();
        Boolean stateIncluded = checkBoxState.isSelected();
        Boolean countryIncluded = checkBoxCountry.isSelected();

        //  Base Query: Shows all attendance data when no filters are applied
        String sqlQuery = "SELECT ud.name, ud.gender, ud.email, ua.date, ua.checkin, ua.status";

        if (enrollmentIncluded) {
            columns.add("Enrollment");
            sqlQuery += ", ud.enrollment_no";
        }
        if (courseIncluded) {
            columns.add("Course");
            sqlQuery += ", ud.course";
        }
        if (departmentIncluded) {
            columns.add("Department");
            sqlQuery += ", ud.department";
        }
        if (stateIncluded) {
            columns.add("State");
            sqlQuery += ", ud.state";
        }
        if (countryIncluded) {
            columns.add("Country");
            sqlQuery += ", ud.country";
        }

        sqlQuery += " FROM userregister AS ud LEFT JOIN attendancedata AS ua ON ud.enrollment_no = ua.enrollment_no";

        //  Apply Filters Only If a Search or Date is Selected
        if (!searchText.isEmpty() || fromDate != null || toDate != null) {
            sqlQuery += " WHERE 1=1"; // Ensures conditions chain correctly

            if (!searchText.isEmpty()) {
                sqlQuery += " AND (ud.name LIKE '%" + searchText + "%' OR ud.enrollment_no LIKE '%" + searchText + "%')";
            }

            if (fromDate != null && toDate != null) {
                sqlQuery += " AND ua.date BETWEEN '" + fromDate + "' AND '" + toDate + "'AND ua.enrollment_no='" + searchText + "'";
            } else if (fromDate != null) {
                sqlQuery += " AND ua.date = '" + fromDate + "' AND ua.enrollment_no = '" + searchText + "'";
            }
        }

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns.toArray());
        userTable.setModel(model);

        try (Connection con = ConnectionProvider.getCon(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sqlQuery)) {

            Long presentCount = 0L;
            Long absentCount = 0L;
            Set<String> enrollmentList = new HashSet<>();

            while (rs.next()) {
                var row = new ArrayList<>();
                row.add(rs.getString("name"));
                row.add(rs.getString("gender"));
                row.add(rs.getString("email"));
                row.add(rs.getString("date"));
                row.add(rs.getString("checkin"));
                row.add(rs.getString("status"));

                if (enrollmentIncluded) {
                    row.add(rs.getString("enrollment_no"));
                    enrollmentList.add(rs.getString("enrollment_no"));
                }
                if (courseIncluded) {
                    row.add(rs.getString("course"));
                }
                if (departmentIncluded) {
                    row.add(rs.getString("department"));
                }
                if (stateIncluded) {
                    row.add(rs.getString("state"));
                }
                if (countryIncluded) {
                    row.add(rs.getString("country"));
                }

                if ("Absent".equals(rs.getString("status"))) {
                    absentCount++;
                } else {
                    presentCount++;
                }

                model.addRow(row.toArray());
            }

            updateAttendanceLabels(enrollmentList, presentCount, absentCount, daysBetween);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong: " + ex.getMessage());
        }
    }

    private LocalDate getLocalDate(JDateChooser chooser) {
        java.util.Date utilDate = chooser.getDate(); // Explicitly define type
        return (utilDate != null) ? utilDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate() : null;
    }

    private void updateAttendanceLabels(Set<String> enrollmentList, Long presentCount, Long absentCount, Long daysBetween) {
        if (enrollmentList.size() == 1) {
            lblPresent.setVisible(true);
            lblAbsent.setVisible(true);
            presentLBL.setVisible(true);
            absentLBL.setVisible(true);
            lblPresent.setText(presentCount.toString());
            lblAbsent.setText((daysBetween != null && daysBetween > presentCount) ? (daysBetween - presentCount) + "" : absentCount.toString());
        } else {
            lblPresent.setVisible(false);
            lblAbsent.setVisible(false);
            presentLBL.setVisible(false);
            absentLBL.setVisible(false);
        }
    }

    private Long countWeekdays(LocalDate start, LocalDate end) {
        long count = 0;
        LocalDate date = start;
        while (!date.isAfter(end)) {
            if (date.getDayOfWeek() != DayOfWeek.SATURDAY && date.getDayOfWeek() != DayOfWeek.SUNDAY) {
                count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }

    private boolean isValidDateRange(String enrollmentNo, LocalDate fromDate, LocalDate toDate) {
        try (Connection con = ConnectionProvider.getCon(); PreparedStatement stmt = con.prepareStatement("SELECT registered_at FROM userregister WHERE enrollment_no = ?")) {

            stmt.setString(1, enrollmentNo);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                LocalDate registeredDate = rs.getDate("registered_at").toLocalDate();

                // Prevent selecting dates before registration
                return !(fromDate != null && fromDate.isBefore(registeredDate))
                        && !(toDate != null && toDate.isBefore(registeredDate))
                        && !(toDate != null && toDate.isAfter(LocalDate.now()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

}
